eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #没有这行你休想访问不同电脑的swagger接口
spring:
  application:
    name: gameplatform-gateway
  cloud:
    config:
      name: gameplatform-gateway #Git上配置文件名称前缀
      discovery:
        enabled: true
        service-id: GAMEPLATFORM-CONFIG  # 注册中心的服务名
      profile: dev  # 指定配置文件的环境
    gateway: #网关路由配置
      routes:
        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: provider_dept_list_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: http://localhost:8001          #匹配后提供服务的路由地址
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/dept/list/**               #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET #只能时 GET 请求时，才能访问
management:
  endpoints:
    web:
      exposure:
        include: refresh

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #设置API网关中路由转发请求的HystrixCommand执行超时时间

ribbon:
  ConnectTimeout: 3000 #设置路由转发请求的时候，创建请求连接的超时时间
  ReadTimeout: 60000  #用来设置路由转发请求的超时时间
